_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
                - 77
            "2":
                - 1
                - 55
                - 77
            "3":
                - 3
                - 13
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
batch_size:
    value: 4
epochs:
    value: 100
learning_rate:
    value: 0.001
model_hidden_dim:
    value: 1024
optimizer:
    value: Adam
